name: ğŸš€ Build & Deploy workflow on prod environment

on:
  pull_request:
    branches: [main]
    types: [closed]

permissions:
  contents: read

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: âœ… ë¸Œëœì¹˜ ì²´í¬ì•„ì›ƒ
        uses: actions/checkout@v3
      - name:  cache-gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: ğŸ“¦ í”„ë¡œì íŠ¸ ë¹Œë“œ
        run: ./gradlew clean build
      - name: ğŸ—ï¸ Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: ğŸ—ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: ğŸ” AWS ECR ë¡œê·¸ì¸
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: ğŸ³ ECR ë¡œê·¸ì¸
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: ğŸ“¦ Docker ì´ë¯¸ì§€ ë¹Œë“œ ë° ECR í‘¸ì‹œ (for ARM64)
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: prod/onetime-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build --platform linux/arm64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --push .

  deploy:
    name: Deploy to Server
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: ğŸ” AWS ìê²© ì¦ëª… ì„¤ì •
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: ğŸš€ ì„œë²„ì— ë°°í¬ ìŠ¤í¬ë¦½íŠ¸ ì‹¤í–‰
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying from GitHub Actions ${{ github.sha }}" \
            --parameters '{"commands":["cd /home/ubuntu/deploy && ./deploy.sh ${{ github.sha }}"]}'
